# Generated by Django 3.2.5 on 2021-10-25 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_link_crated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='link',
            name='crated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
